import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="Nav-Bar" class="container py-6 flex items-center justify-between"> 
        <nav> 
          <ul class="flex items-center gap-4">
           <Link href={"/"}> Home </Link>
           <Link href={"/Search"}> Search</Link>
           <Link href={"/Calculator"}> Calculator </Link>
           <Link href={"/Trading"}> Trade </Link>
           <Link href={"/Collection"}> Collection </Link>
           <Link href={"/User"}> User </Link>
          </ul>
        </nav>
      </div> 

       
        {children}
      </body>
    </html>
  );
}
